extends Node
## Lightweight sound effect player. Sounds live in res://assets/audio/<name>.wav
## (generated by tools/gen_sfx.py). Positional sounds are attenuated by distance to the camera.

const AUDIO_DIR: String = "res://assets/audio/"
const POOL_SIZE: int = 16
const HEARING_RANGE: float = 38.0

var _streams: Dictionary = {}
var _pool: Array[AudioStreamPlayer] = []
var _next: int = 0
var _enabled: bool = true
var _last_played: Dictionary = {}


func _ready() -> void:
	_enabled = DisplayServer.get_name() != "headless"
	if not _enabled:
		return
	for i: int in range(POOL_SIZE):
		var player := AudioStreamPlayer.new()
		add_child(player)
		_pool.append(player)


func _get_stream(sound: String) -> AudioStream:
	if _streams.has(sound):
		return _streams[sound]
	var path: String = AUDIO_DIR + sound + ".wav"
	var stream: AudioStream = load(path) as AudioStream if ResourceLoader.exists(path) else null
	_streams[sound] = stream
	return stream


func play(sound: String, volume_db: float = 0.0, pitch_variation: float = 0.05) -> void:
	if not _enabled or sound.is_empty():
		return
	var stream: AudioStream = _get_stream(sound)
	if stream == null:
		return
	# Avoid stacking the exact same sound many times in one frame (e.g. volley hits).
	var now: int = Time.get_ticks_msec()
	if now - int(_last_played.get(sound, -1000)) < 35:
		return
	_last_played[sound] = now
	var player: AudioStreamPlayer = _pool[_next]
	_next = (_next + 1) % _pool.size()
	player.stream = stream
	player.volume_db = volume_db + linear_to_db(maxf(Settings.sfx_volume, 0.0001))
	player.pitch_scale = 1.0 + randf_range(-pitch_variation, pitch_variation)
	player.play()


## Plays a world sound, quieter the further it is from the camera.
func play_at(sound: String, world_position: Vector3, volume_db: float = 0.0) -> void:
	if not _enabled:
		return
	var game := Game.current
	if game and game.camera_rig:
		var focus: Vector3 = game.camera_rig.focus
		var distance: float = Vector2(focus.x - world_position.x, focus.z - world_position.z).length()
		if distance > HEARING_RANGE:
			return
		volume_db += linear_to_db(clampf(1.0 - distance / HEARING_RANGE, 0.05, 1.0))
	play(sound, volume_db)
